# Generated by Django 6.0.2 on 2026-03-27 07:57

import awis_custom_settings.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatamodel',
            name='role',
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='role',
            field=models.IntegerField(choices=[(0, 'Outside'), (10, 'Employee'), (11, 'Manager'), (12, 'Director'), (99, 'System Admin')], default=awis_custom_settings.settings.RoleList['EMPLOYEE']),
        ),
    ]
