# Generated by Django 6.0.2 on 2026-03-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodel',
            name='role',
            field=models.IntegerField(choices=[(0, 'Outside'), (10, 'Employee'), (11, 'Manager'), (12, 'Director'), (99, 'System Admin')]),
        ),
    ]
