# Generated by Django 6.0.2 on 2026-03-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userdatamodel_role_alter_useraccess_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='role',
            field=models.IntegerField(choices=[(0, 'Outside'), (10, 'Employee'), (11, 'Manager'), (12, 'Director'), (99, 'System Admin')], default=10),
        ),
    ]
