# Generated by Django 6.0.2 on 2026-03-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Director', 'Director')], default='Employee', max_length=50),
        ),
    ]
