# Generated by Django 6.0.2 on 2026-03-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_adminPanel', ''), ('create_adminPanel', ''), ('edit_adminPanel', ''), ('delete_adminPanel', ''), ('approve_adminPanel', ''), ('view_reqformAwaitApproval', ''), ('create_reqformAwaitApproval', ''), ('edit_reqformAwaitApproval', ''), ('delete_reqformAwaitApproval', ''), ('approve_reqformAwaitApproval', ''), ('view_reqformSubmitted', ''), ('create_reqformSubmitted', ''), ('edit_reqformSubmitted', ''), ('delete_reqformSubmitted', ''), ('approve_reqformSubmitted', '')],
                'default_permissions': (),
            },
        ),
    ]
