# Generated by Django 6.0.2 on 2026-04-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useraccess_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('action', models.CharField(max_length=100)),
                ('system', models.CharField(max_length=100)),
                ('time_logged', models.DateTimeField()),
                ('relevant_info', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(choices=[('normal', 'normal'), ('errors', 'errors'), ('denied', 'denied')], max_length=6)),
                ('url_path', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
