# Generated by Django 6.0.2 on 2026-03-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useraccess_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('action', models.CharField()),
                ('system', models.CharField()),
                ('time_logged', models.DateTimeField()),
            ],
        ),
    ]
