# Generated by Django 6.0.2 on 2026-04-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_logsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='role',
            field=models.IntegerField(choices=[(0, 'Outside'), (10, 'Employee'), (11, 'Manager'), (12, 'Director'), (99, 'System Admin'), (98, 'Court User')], default=10),
        ),
    ]
