# Generated by Django 6.0.2 on 2026-03-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_logsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsystem',
            name='relevant_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
