# Generated by Django 6.0.2 on 2026-04-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_logsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='role',
            field=models.IntegerField(choices=[(10, 'เจ้าหน้าที่'), (11, 'ผู้อนุมัติ'), (12, 'ผู้ดูแลระดับฝ่าย'), (99, 'ผู้ดูแลระบบ'), (98, 'เจ้าหน้าที่ของศาล')], default=10),
        ),
    ]
