# Generated by Django 6.0.2 on 2026-05-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSelectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('hash_hex_str', models.CharField(max_length=40)),
                ('data', models.JSONField(default=dict)),
                ('prev_data', models.JSONField(default=dict)),
            ],
        ),
    ]
