# Generated by Django 6.0.2 on 2026-05-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_api_key', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=16)),
                ('permissions', models.JSONField(default=list)),
            ],
        ),
    ]
