# Generated by Django 6.0.2 on 2026-05-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apisecret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisecret',
            name='permissions',
            field=models.JSONField(default=dict),
        ),
    ]
