# Generated by Django 6.0.2 on 2026-05-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_apisecret_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('last_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
