# Generated by Django 6.0.2 on 2026-03-06 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('warrant_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recive_date', models.DateTimeField()),
                ('accept_date', models.DateTimeField()),
                ('accept', models.IntegerField(choices=[(0, 'ไม่รับ'), (1, 'รับ')])),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warrant_form.mainawisdatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='FormApprovalDataContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('approve_status', models.IntegerField(choices=[(0, 'ไม่ผ่านการอนุมติ'), (1, 'กำลังรอพิจารณา'), (2, 'ผ่านการอนุมัติ')])),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warrant_form.mainawisdatamodel')),
                ('form_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_form', to='users.userdatamodel')),
                ('form_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_form', to='users.userdatamodel')),
            ],
            options={
                'permissions': [('can_approve_form', 'Can approve form')],
            },
        ),
        migrations.CreateModel(
            name='VisualFinalizedFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recive_date', models.DateTimeField(blank=True, null=True)),
                ('accept_date', models.DateTimeField(blank=True, null=True)),
                ('accept', models.IntegerField(blank=True, choices=[(0, 'ไม่รับ'), (1, 'รับ'), (99, 'รอการพิจารณา')], null=True)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warrant_form.reqformdatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='VisualFormApprovalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('approve_status', models.IntegerField(choices=[(0, 'ไม่ผ่านการอนุมติ'), (1, 'กำลังรอพิจารณา'), (2, 'ผ่านการอนุมัติ')])),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warrant_form.reqformdatamodel')),
                ('form_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visual_form', to='users.userdatamodel')),
                ('form_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_visual_form', to='users.userdatamodel')),
            ],
            options={
                'permissions': [('can_approve_form', 'Can approve form')],
            },
        ),
    ]
