# Generated by Django 6.0.2 on 2026-03-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warrant_form', '0002_alter_reqformdatamodel_judge_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualReqformData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recive_date', models.DateTimeField(blank=True, null=True)),
                ('accept_date', models.DateTimeField(blank=True, null=True)),
                ('accept', models.IntegerField(blank=True, choices=[(0, 'ไม่รับ'), (1, 'รับ'), (99, 'รอการพิจารณา')], null=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VisualWarrantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_name', models.CharField(max_length=250)),
                ('court_injunction', models.IntegerField(blank=True, choices=[(0, 'ไม่อนุมัติ'), (1, 'อนุมัติ'), (99, 'รอการพิจารณา')], null=True)),
                ('injunction_date', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=250)),
                ('because', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FormAwaitingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('approve_status', models.IntegerField(choices=[(0, 'ไม่ผ่านการอนุมติ'), (1, 'กำลังรอพิจารณา'), (2, 'ผ่านการอนุมัติ')])),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warrant_form.reqformdatamodel')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
