# Generated by Django 6.0.2 on 2026-05-05 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualreqformdata',
            name='recive_date',
        ),
    ]
