# Generated by Django 6.0.2 on 2026-03-24 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('warrant_form', '0002_alter_reqformdatamodel_judge_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formawaitingapproval',
            name='form_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visual_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formawaitingapproval',
            name='form_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_visual_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visualreqformdata',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_form', to='warrant_form.reqformdatamodel'),
        ),
        migrations.AddField(
            model_name='visualwarrantdata',
            name='warrant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_warrant', to='warrant_form.warrantdatamodel'),
        ),
    ]
