# Generated by Django 6.0.2 on 2026-03-05 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0001_initial'),
        ('warrant_form', '0003_reqformdatamodel_woa_end_date_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualFinalizedFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recive_date', models.DateTimeField()),
                ('accept_date', models.DateTimeField()),
                ('accept', models.IntegerField(choices=[(0, 'ไม่รับ'), (1, 'รับ')])),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warrant_form.reqformdatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='VisualFormApprovalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('approve_status', models.IntegerField(choices=[(0, 'ไม่ผ่านการอนุมติ'), (1, 'กำลังรอพิจารณา'), (2, 'ผ่านการอนุมัติ')])),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warrant_form.reqformdatamodel')),
                ('form_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visual_form', to='users.userdatamodel')),
                ('form_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_visual_form', to='users.userdatamodel')),
            ],
            options={
                'permissions': [('can_approve_form', 'Can approve form')],
            },
        ),
    ]
