# Generated by Django 6.0.2 on 2026-05-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_visualreqformdata_recive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualwarrantdata',
            name='report_status',
            field=models.IntegerField(choices=[(0, 'ยังไม่ได้รายงาน'), (1, 'รายงานแล้ว')], default=0),
        ),
    ]
