# Generated by Django 6.0.2 on 2026-03-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_visualfinalizedformdata_visualformapprovaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualfinalizedformdata',
            name='accept',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่รับ'), (1, 'รับ'), (99, 'รอการพิจารณา')], null=True),
        ),
        migrations.AlterField(
            model_name='visualfinalizedformdata',
            name='accept_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualfinalizedformdata',
            name='recive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
