# Generated by Django 6.0.2 on 2026-03-06 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_visualfinalizedformdata_accept_and_more'),
        ('warrant_form', '0003_reqformdatamodel_woa_end_date_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualfinalizedformdata',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_form', to='warrant_form.reqformdatamodel'),
        ),
    ]
