# Generated by Django 6.0.2 on 2026-05-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_visualwarrantdata_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualwarrantdata',
            name='judge_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
