# Generated by Django 6.0.2 on 2026-05-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_visualwarrantdata_judge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualreqformdata',
            name='accept',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่รับ'), (1, 'รับ'), (99, 'รอศาลตอบรับ')], null=True),
        ),
    ]
