# Generated by Django 6.0.2 on 2026-05-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_visualreqformdata_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formawaitingapproval',
            name='approve_status',
            field=models.IntegerField(choices=[(0, 'ไม่ผ่านการอนุมติ'), (1, 'กำลังรอพิจารณา'), (2, 'ผ่านการอนุมัติ')], default=1),
        ),
        migrations.AlterField(
            model_name='visualreqformdata',
            name='accept',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่รับ'), (1, 'รับ'), (99, 'รอศาลตอบรับ')], default=99, null=True),
        ),
        migrations.AlterField(
            model_name='visualwarrantdata',
            name='court_injunction',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่อนุมัติ'), (1, 'อนุมัติ'), (99, 'รอการพิจารณา')], default=99, null=True),
        ),
    ]
