# Generated by Django 6.0.2 on 2026-05-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_formawaitingapproval_approve_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formawaitingapproval',
            name='approve_status',
            field=models.IntegerField(choices=[(-1, 'ยกเลิก'), (0, 'ไม่ผ่านการพิจารณา'), (1, 'กำลังรอพิจารณา'), (2, 'ผ่านการพิจารณา')], default=1),
        ),
    ]
