# Generated by Django 6.0.2 on 2026-02-12 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrayWarrantDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woa_date', models.CharField(max_length=10)),
                ('fault_type_id', models.IntegerField()),
                ('send_to_name', models.CharField(max_length=250)),
                ('cause_text', models.CharField(max_length=400)),
                ('charge', models.CharField(max_length=250)),
                ('charge_type_1', models.IntegerField()),
                ('charge_type_2', models.IntegerField()),
                ('charge_type_2_1', models.IntegerField()),
                ('charge_type_2_2', models.IntegerField()),
                ('charge_type_2_3', models.IntegerField()),
                ('charge_type_3', models.IntegerField()),
                ('charge_other_text', models.CharField(max_length=250)),
                ('acc_full_name', models.CharField(max_length=250)),
                ('acc_card_type', models.IntegerField()),
                ('acc_card_id', models.CharField(max_length=20)),
                ('acc_origin', models.IntegerField()),
                ('acc_nation', models.IntegerField()),
                ('acc_occupation', models.CharField(max_length=100)),
                ('acc_addno', models.CharField(max_length=50)),
                ('acc_vilno', models.CharField(max_length=50)),
                ('acc_road', models.CharField(max_length=100)),
                ('acc_soi', models.CharField(max_length=100)),
                ('acc_near', models.CharField(max_length=200)),
                ('acc_sub_district', models.CharField(max_length=6)),
                ('acc_district', models.CharField(max_length=4)),
                ('acc_province', models.CharField(max_length=2)),
                ('acc_tel', models.CharField(max_length=20)),
                ('appointment_type', models.IntegerField()),
                ('appointment_date', models.CharField(max_length=19)),
                ('woa_start_date', models.CharField(max_length=10)),
                ('woa_end_date', models.CharField(max_length=10)),
                ('woa_refno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MainJSONWarrantDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_code', models.CharField(max_length=7)),
                ('req_year', models.IntegerField()),
                ('req_year_type_id', models.IntegerField()),
                ('police_station_id', models.CharField(max_length=5)),
                ('req_no_plaintiff', models.CharField(max_length=50)),
                ('plaintiff', models.CharField(max_length=400)),
                ('accused', models.CharField(max_length=400)),
                ('req_name', models.CharField(max_length=300)),
                ('req_pos', models.CharField(max_length=400)),
                ('req_age', models.IntegerField()),
                ('req_office', models.CharField(max_length=300)),
                ('req_sub_district', models.CharField(max_length=6)),
                ('req_district', models.CharField(max_length=4)),
                ('req_province', models.CharField(max_length=2)),
                ('req_tel', models.CharField(max_length=50)),
                ('cause_type_id', models.IntegerField()),
                ('cause_text', models.CharField(max_length=500)),
                ('charge', models.CharField(max_length=50)),
                ('charge_type_1', models.IntegerField()),
                ('charge_type_2', models.IntegerField()),
                ('scene', models.CharField(max_length=300)),
                ('scene_date', models.CharField(max_length=19)),
                ('act', models.CharField(max_length=500)),
                ('law', models.CharField(max_length=200)),
                ('court_owner_code', models.CharField(max_length=7)),
                ('prescription', models.IntegerField()),
                ('agent_name', models.CharField(max_length=400)),
                ('agent_pos', models.CharField(max_length=400)),
                ('have_req', models.IntegerField()),
                ('have_court_code', models.CharField(max_length=7)),
                ('have_act', models.CharField(max_length=400)),
                ('have_injunc', models.CharField(max_length=50)),
                ('composer_name', models.CharField(max_length=200)),
                ('composer_position', models.CharField(max_length=200)),
                ('writer_name', models.CharField(max_length=200)),
                ('write_position', models.CharField(max_length=200)),
                ('create_uid', models.IntegerField()),
                ('ref_no', models.CharField(max_length=50)),
                ('warrants', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warrant_form.arraywarrantdatamodel')),
            ],
        ),
    ]
