# Generated by Django 6.0.2 on 2026-03-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainawisdatamodel',
            name='police_station_id',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='mainawisdatamodel',
            name='woa_end_date',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='mainawisdatamodel',
            name='woa_start_date',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='warrantdatamodel',
            name='woa_date',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
