# Generated by Django 6.0.2 on 2026-03-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqformdatamodel',
            name='req_form_number',
            field=models.IntegerField(),
        ),
    ]
