# Generated by Django 6.0.2 on 2026-03-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantdatamodel',
            name='acc_card_type',
            field=models.IntegerField(blank=True, choices=[(1, 'เลขประจำตัวประชาชน'), (2, 'เลขหนังสือเดินทาง'), (3, 'เลขคนซึ่งไม่มีสัญชาติไทย')], null=True),
        ),
    ]
