# Generated by Django 6.0.2 on 2026-02-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialawisdataformmodelpartone',
            name='scene_date_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
