# Generated by Django 6.0.2 on 2026-03-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqformdatamodel',
            name='judge_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
