# Generated by Django 6.0.2 on 2026-03-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reqformdatamodel',
            old_name='writer_position',
            new_name='write_position',
        ),
        migrations.RemoveField(
            model_name='reqformdatamodel',
            name='scene_date',
        ),
        migrations.AddField(
            model_name='reqformdatamodel',
            name='warrants',
            field=models.ManyToManyField(to='warrant_form.warrantdatamodel'),
        ),
    ]
