# Generated by Django 6.0.2 on 2026-03-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantdatamodel',
            name='court_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='warrantdatamodel',
            name='plaintiff',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
