# Generated by Django 6.0.2 on 2026-04-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0002_formdraftcontainer_reqformdraftdatamodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqformdraftdatamodel',
            name='reqno',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
