# Generated by Django 6.0.2 on 2026-03-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0002_rename_writer_position_reqformdatamodel_write_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqformdatamodel',
            name='woa_end_date_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqformdatamodel',
            name='woa_end_date_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqformdatamodel',
            name='woa_end_date_timehalf',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqformdatamodel',
            name='woa_end_date_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqformdatamodel',
            name='woa_start_date_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqformdatamodel',
            name='woa_start_date_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqformdatamodel',
            name='woa_start_date_timehalf',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqformdatamodel',
            name='woa_start_date_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
