# Generated by Django 6.0.2 on 2026-04-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0002_formdraftcontainer_reqformdraftdatamodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdraftcontainer',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
