# Generated by Django 6.0.2 on 2026-03-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0003_reqformdatamodel_woa_end_date_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantdatamodel',
            name='woa_date',
        ),
        migrations.AddField(
            model_name='warrantdatamodel',
            name='woa_date_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantdatamodel',
            name='woa_date_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantdatamodel',
            name='woa_date_timehalf',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantdatamodel',
            name='woa_date_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantdatamodel',
            name='woa_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MainAWISDataModel',
        ),
    ]
