# Generated by Django 6.0.2 on 2026-03-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0004_remove_warrantdatamodel_woa_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantdatamodel',
            name='appointment_date',
        ),
        migrations.AddField(
            model_name='warrantdatamodel',
            name='appointment_date_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantdatamodel',
            name='appointment_date_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantdatamodel',
            name='appointment_date_timehalf',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantdatamodel',
            name='appointment_date_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
