# Generated by Django 6.0.2 on 2026-04-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0004_remove_reqformdatamodel_court_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqformdatamodel',
            name='court_owner_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='ซึ่งเป็นคดีที่อยู่ในอำนาจศาล'),
        ),
        migrations.AlterField(
            model_name='reqformdatamodel',
            name='have_court_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='reqformdatamodel',
            name='req_no_plaintiff',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
