# Generated by Django 6.0.2 on 2026-04-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0005_alter_reqformdatamodel_court_owner_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqformdraftdatamodel',
            name='court_owner_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='ซึ่งเป็นคดีที่อยู่ในอำนาจศาล'),
        ),
        migrations.AlterField(
            model_name='reqformdraftdatamodel',
            name='have_court_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
