# Generated by Django 6.0.2 on 2026-04-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0006_alter_reqformdraftdatamodel_court_owner_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqformdraftdatamodel',
            name='req_case_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
