# Generated by Django 6.0.2 on 2026-04-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0007_alter_reqformdraftdatamodel_req_case_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqformdatamodel',
            name='reqno',
        ),
        migrations.RemoveField(
            model_name='reqformdraftdatamodel',
            name='req_day',
        ),
        migrations.RemoveField(
            model_name='reqformdraftdatamodel',
            name='req_form_number',
        ),
        migrations.RemoveField(
            model_name='reqformdraftdatamodel',
            name='req_month',
        ),
        migrations.RemoveField(
            model_name='reqformdraftdatamodel',
            name='req_year',
        ),
        migrations.RemoveField(
            model_name='reqformdraftdatamodel',
            name='reqno',
        ),
        migrations.AlterField(
            model_name='reqformdatamodel',
            name='req_form_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
