# Generated by Django 6.0.2 on 2026-05-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0008_remove_reqformdatamodel_reqno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantdraftdatamodel',
            name='woa_no',
        ),
        migrations.AddField(
            model_name='warrantdatamodel',
            name='woa_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warrantdatamodel',
            name='woa_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
