# Generated by Django 6.0.2 on 2026-05-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0009_remove_warrantdraftdatamodel_woa_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqformdatamodel',
            name='req_day',
        ),
        migrations.RemoveField(
            model_name='reqformdatamodel',
            name='req_month',
        ),
        migrations.AddField(
            model_name='reqformdatamodel',
            name='req_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
