# Generated by Django 6.0.2 on 2026-05-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0010_remove_reqformdatamodel_req_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantdatamodel',
            name='woa_refno',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
