# Generated by Django 6.0.2 on 2026-05-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0011_alter_warrantdatamodel_woa_refno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqformdatamodel',
            name='court_code',
            field=models.CharField(max_length=8),
        ),
    ]
