# Generated by Django 6.0.2 on 2026-05-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0012_alter_reqformdatamodel_court_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqformdatamodel',
            name='cause_text',
            field=models.TextField(blank=True),
        ),
    ]
