# Generated by Django 6.0.2 on 2026-05-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0013_alter_reqformdatamodel_cause_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqformdatamodel',
            name='cause_text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
