# Generated by Django 6.0.2 on 2026-05-20 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0014_alter_reqformdatamodel_cause_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqformdatamodel',
            name='draft_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='warrant_form.reqformdraftdatamodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reqformdatamodel',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
