# Generated by Django 6.0.2 on 2026-05-25 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0015_reqformdatamodel_draft_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqformdatamodel',
            name='draft_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='warrant_form.reqformdraftdatamodel'),
        ),
    ]
