# Generated by Django 6.0.2 on 2026-05-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0016_alter_reqformdatamodel_draft_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqformdraftdatamodel',
            name='req_case_type_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='warrantdraftdatamodel',
            name='fault_type_id',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='warrantdraftdatamodel',
            name='woa_type',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
