# Generated by Django 6.0.2 on 2026-06-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0017_alter_reqformdraftdatamodel_req_case_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqformdatamodel',
            name='cause_text_piece_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reqformdatamodel',
            name='cause_text_piece_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reqformdatamodel',
            name='cause_text_piece_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reqformdraftdatamodel',
            name='cause_text_piece_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reqformdraftdatamodel',
            name='cause_text_piece_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reqformdraftdatamodel',
            name='cause_text_piece_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reqformdraftdatamodel',
            name='cause_text_piece_4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
