# Generated by Django 6.0.2 on 2026-06-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0018_reqformdatamodel_cause_text_piece_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqformdatamodel',
            name='acc_title',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reqformdatamodel',
            name='req_title',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reqformdraftdatamodel',
            name='acc_title',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reqformdraftdatamodel',
            name='req_title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
