# Generated by Django 6.0.2 on 2026-06-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant_form', '0019_reqformdatamodel_acc_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqformdatamodel',
            name='cause_text_piece_4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
